name: nixbuild.net
description: Run Nix builds on nixbuild.net
author: Rickard Nilsson

inputs:

  nixbuild_ssh_key:
    required: true
    description: |
      The private ssh key used to authenticate with nixbuild.net

      You should not add your private key directly to the workflow file but
      instead define a GitHub Secret for it, to avoid mistakenly sharing your
      key with others.

      It is advisable to create a new nixbuild.net ssh key specifically for
      use within GitHub (or even per repository or workflow). That way you can
      revoke access to your nixbuild.net account in a fine-grained fashion.

      See the README of this action for easy setup instructions.


  generate_summary_for:
    required: false
    default: ''
    description: |
      If set to 'job', a summary of all builds and their resource usage will be
      generated as a GitHub Actions step summary for the job that used
      nixbuild-action.

      If set to 'workflow', the summary will instead include builds from all
      jobs executed so far during the workflow run. A workflow summary makes
      most sense for the very last job in your workflow (since it can be
      incomplete otherwise).

      If set to '', no summary will be generated.


  allow-override:
    required: false
    description: |
      Set the allow-override setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#allow-override.

      Note, all inputs to this action is communicated to nixbuild.net through
      the SSH environment. That means disabling allow-override here can only
      stop settings overrides from Nix derivations, no other levels. See the
      nixbuild.net settings documentation for more info on this.

  reuse-build-failures:
    required: false
    description: |
      Set the reuse-build-failures setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#reuse-build-failures.

  reuse-build-timeouts:
    required: false
    description: |
      Set the reuse-build-timeouts setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#reuse-build-timeouts.

  keep-builds-running:
    required: false
    description: |
      Set the keep-builds-running setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#keep-builds-running.

runs:
  using: 'node16'
  main: 'index.js'
  post: 'summary.js'

branding:
  icon: zap
  color: gray-dark
