name: nixbuild.net
description: Run Nix builds on nixbuild.net
author: Rickard Nilsson

inputs:

  nixbuild_ssh_key:
    required: true
    description: |
      The private ssh key used to authenticate with nixbuild.net

      You should not add your private key directly to the workflow file but
      instead define a GitHub Secret for it, to avoid mistakenly sharing your
      key with others.

      It is advisable to create a new nixbuild.net ssh key specifically for
      use within GitHub (or even per repository or workflow). That way you can
      revoke access to your nixbuild.net account in a fine-grained fashion.

      See the README of this action for easy setup instructions.

  cache-build-failures:
    required: false
    description: |
      Set the cache-build-failures setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#cache-build-failures.

  cache-build-timeouts:
    required: false
    description: |
      Set the cache-build-timeouts setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#cache-build-timeouts.

  keep-builds-running:
    required: false
    description: |
      Set the keep-builds-running setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#keep-builds-running.

  always-substitute:
    required: false
    description: |
      Set the always-substitute setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#always-substitute.

      Note that this setting is actually ignored for builds performed by this
      GitHub Action, because the action enables the Nix setting
      builders-use-substitutes so substitution will always be used anyway
      (unless the never-substitute setting is active).

  never-substitute:
    required: false
    description: |
      Set the never-substitute setting in nixbuild.net. For documentation
      see https://docs.nixbuild.net/settings/#never-substitute.


runs:
  using: "composite"
  steps:
    - name: Setup Nix for nixbuild.net
      run: ${{ github.action_path }}/nixbuild-action.sh
      shell: bash
      env:
        INPUTS_JSON: ${{ toJSON(inputs) }}
        NIXBUILD_SSH_KEY: ${{ inputs.nixbuild_ssh_key }}
        ACTION_LIB: ${{ github.action_path }}/lib


branding:
  icon: zap
  color: gray-dark
