name: CI Workflow Example

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    uses: ./.github/workflows/ci-workflow.yml
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
    with:
      # All settings are optional, the CI Workflow has usable defaults
      # The available settings are documented in ./ci-workflow.yml

      # By default the CI Workflow uses flake.nix from the repository root, but
      # we want it to use our example flake here
      flake_directory: examples/using-the-ci-workflow

      # Tweak the label shown for each job. This is done with a jq expression
      # that produces a string based on the build's fields
      label_builds: '"\(.attr).\(.system)"'

      # We can filter which attributes to build by configuring a jq expression
      # producing a boolean based on the build's fields. We use the same
      # expression that the CI Workflow uses by default here (build everything
      # in the flake's `checks` attribute).
      filter_builds: '.top_attr == "checks"'

  results:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - run: echo "${{ needs.checks.outputs.results }}" | jq .
