name: nixbuild-ci

on:
  workflow_call:
    secrets:
      nixbuild_ssh_key:
        required: true
        description: |
          The private ssh key used to authenticate with nixbuild.net

          You should not add your private key directly to the workflow file but
          instead define a GitHub Secret for it, to avoid mistakenly sharing your
          key with others.

          It is advisable to create a new nixbuild.net ssh key specifically for
          use within GitHub (or even per repository or workflow). That way you can
          revoke access to your nixbuild.net account in a fine-grained fashion.

    inputs:
      filter_builds:
        type: string
        required: false
        default: '.top_attr == "checks"'

      label_builds:
        type: string
        required: false
        default: '"\(.attr) [\(.system)]"'

      flake_directory:
        type: string
        required: false
        default: '.'

      pre_evaluation_script:
        type: string
        required: false
        default: ''

      pre_build_script:
        type: string
        required: false
        default: ''


jobs:

  eval-flake:
    name: "evaluate flake"
    runs-on: ubuntu-latest
    outputs:
      builds: ${{ steps.find-builds.outputs.builds }}
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v12
        with:
          nix_on_tmpfs: true
          nix_conf: experimental-features = nix-command flakes
      - name: Pre-evaluation script
        run: ${{inputs.pre_evaluation_script}}
      - name: Find builds
        id: find-builds
        run: |
          set -eo pipefail
          flake_json="$(mktemp)"
          builds="$(mktemp)"
          nix flake show "${{inputs.flake_directory}}" --json > "$flake_json"
          jq < "$flake_json" -rc '{checks: (.checks // {}), packages: (.packages // {})}|to_entries|map(.key as $top_attr | .value|to_entries|map(.key as $sys | .value|to_entries|map(.key as $attr | .value + {top_attr: $top_attr, system: $sys, attr: $attr})))|flatten|map(select(${{inputs.filter_builds}}))|map(. as $x | (${{inputs.label_builds}}) as $l | $x + {label: $l})|"::set-output name=builds::\(.)"'

  build:
    name: ${{matrix.build.label}}
    needs: eval-flake
    strategy:
      fail-fast: false
      matrix:
        build: ${{fromJSON(needs.eval-flake.outputs.builds)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v12
        with:
          nix_on_tmpfs: true
          nix_conf: experimental-features = nix-command flakes
      - uses: nixbuild/nixbuild-action@v9
        with:
          nixbuild_ssh_key: ${{secrets.nixbuild_ssh_key}}

      - name: Pre-build script
        run: ${{inputs.pre_build_script}}

      - name: "Build ${{matrix.build.top_attr}}.${{matrix.build.system}}.${{matrix.build.attr}}"
        run: |
          nix build "${{inputs.flake_directory}}#${{matrix.build.top_attr}}.${{matrix.build.system}}.${{matrix.build.attr}}" \
            --print-build-logs \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net
