name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    needs:
      - install-with-nix-quick-install-action
      - install-with-install-nix-action
      - test-build
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: experimental-features = nix-command flakes
      - uses: ./
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      - name: Build release script
        run: nix build .#packages.x86_64-linux.release
      - name: Verify build signature
        run: test "$(nix path-info ./result --json | jq -r '.[].signatures[0]' | sed 's/:.*//')" = "nixbuild.net/rickard-1"
      - name: Release if needed
        if: github.ref == 'refs/heads/master'
        run: ./result ${{steps.nix-archives.outputs.download-path}} ./RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15 ]
        system: [ x86_64-linux ]
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: experimental-features = nix-command flakes
      - uses: ./
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
          keep-builds-running: true # test that we can set a setting
      - name: Run a test build
        run: nix build --system ${{ matrix.system }} .#simple-test-build
      - name: Verify build signature
        run: test "$(nix path-info ./result --json | jq -r '.[].signatures[0]' | sed 's/:.*//')" = "nixbuild.net/rickard-1"


  install-with-nix-quick-install-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15 ]
        nix_version:
          - 2.4pre20210908_3c56f62
          - 2.4pre20210601_5985b8b
          - 2.4pre20201205_a5d85d0
          - 2.3.15
          - 2.3.14
          - 2.3.12
          - 2.3.10
          - 2.3.7
          - 2.2.2
          - 2.1.3
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: ${{ matrix.nix_version }}
      - uses: ./
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
          keep-builds-running: true # test that we can set a setting


  install-with-install-nix-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
      - uses: ./
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
          keep-builds-running: true # test that we can set a setting
